FROM python:3.10

# Installer dépendances système
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    libpq-dev \
    python3-dev \
    build-essential

# Cloner Odoo
RUN git clone https://github.com/odoo/odoo.git /odoo

WORKDIR /odoo

# Installer dépendances Python
COPY requirements.txt /odoo/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copier config Odoo
COPY odoo.conf /etc/odoo/odoo.conf

# Port Render
EXPOSE 10000

# Lancer Odoo
CMD ["python", "odoo-bin", "-c", "/etc/odoo/odoo.conf", "--http-port", "10000"]
