[options]
db_host = dpg-d7o8i1nlk1mc7385qja0-a.render.com
db_user = gestion_commercialeodoo_user
db_password = FIQQmNoswQCSR5LHIgih57xzKIy93LF0
db_port = 5432
db_sslmode = require
xmlrpc_interface = 0.0.0.0
xmlrpc_port = 8069
